[package]
name = "whisped"
version = "0.1.0"
edition = "2024"

[features]
cuda = ["whisper-rs/cuda"]
vulkan = ["whisper-rs/vulkan"]

[dependencies]
argh = "0.1.19"
dirs = "7.0.0"
hound = "3.5.1"
lewton = "0.10.2"
minimp3 = { version = "0.6.1", features = ["async_tokio"] }
reqwest = "0.13.5"
rubato = "5.0.0"
sha1 = "0.10"
tokio = { version = "1.53.1", features = ["fs", "macros", "rt-multi-thread"] }
whisper-rs = "0.16.0"
